from __future__ import annotations

from bisect import bisect_left
from datetime import datetime, timedelta
from decimal import Decimal

from .models import CandidateOutcome, Kline
from .protocol import SplitBoundaries, assign_split


def _bar_map(bars: list[Kline]) -> dict[datetime, Kline]:
    return {bar.open_time: bar for bar in bars}


def candidate_times(
    bars_15m: list[Kline],
    start: datetime,
    end: datetime,
    boundaries: SplitBoundaries,
    *,
    horizon_minutes: int = 480,
    cadence_minutes: int = 15,
) -> list[datetime]:
    """Every eligible 15-minute timestamp generated by one identical process.

    A candidate is included only when its entry bar exists, has at least one
    trade, and the complete forward outcome window is present at the expected
    cadence. Missing market data therefore cannot silently become a negative.
    """
    expected_bars = horizon_minutes // cadence_minutes
    decisions: list[datetime] = []
    for idx, bar in enumerate(bars_15m):
        if not (start <= bar.open_time < end):
            continue
        if bar.trades <= 0 or bar.open <= 0 or assign_split(bar.open_time, boundaries) == 'embargo':
            continue
        forward = bars_15m[idx:idx + expected_bars]
        if len(forward) != expected_bars:
            continue
        if any(
            item.open_time != bar.open_time + timedelta(minutes=cadence_minutes * offset)
            for offset, item in enumerate(forward)
        ):
            continue
        decisions.append(bar.open_time)
    return decisions


def coarse_positive_times(
    bars_15m: list[Kline],
    decisions: list[datetime],
    *,
    threshold_pct: Decimal,
    horizon_minutes: int,
) -> set[datetime]:
    """Find decision timestamps whose forward 15-minute highs can reach target.

    This is outcome computation, not predictor engineering. The entry is the
    interval open: Binance defines it as the first trade price in that interval.
    """
    by_time = _bar_map(bars_15m)
    times = [bar.open_time for bar in bars_15m]
    threshold_multiple = Decimal('1') + threshold_pct / Decimal('100')
    horizon = timedelta(minutes=horizon_minutes)
    positives: set[datetime] = set()
    for decision in decisions:
        entry = by_time[decision]
        target = entry.open * threshold_multiple
        index = bisect_left(times, decision)
        cursor = index
        while cursor < len(bars_15m) and bars_15m[cursor].open_time < decision + horizon:
            if bars_15m[cursor].high >= target:
                positives.add(decision)
                break
            cursor += 1
    return positives


def overlapping_groups(decisions: list[datetime], horizon_minutes: int) -> list[tuple[datetime, datetime]]:
    """Merge positive candidate forward windows to minimise one-minute API calls."""
    if not decisions:
        return []
    horizon = timedelta(minutes=horizon_minutes)
    ordered = sorted(decisions)
    groups: list[tuple[datetime, datetime]] = []
    start = ordered[0]
    end = ordered[0] + horizon
    for decision in ordered[1:]:
        candidate_end = decision + horizon
        if decision <= end:
            end = max(end, candidate_end)
        else:
            groups.append((start, end))
            start, end = decision, candidate_end
    groups.append((start, end))
    return groups


def evaluate_candidate(
    decision_time: datetime,
    split: str,
    bars_15m: list[Kline],
    bars_1m: list[Kline] | None,
    *,
    threshold_pct: Decimal = Decimal('10'),
    horizon_minutes: int = 480,
    entry_liquidity_minutes: int = 15,
    exit_liquidity_minutes: int = 5,
    min_entry_notional: Decimal = Decimal('500'),
    min_exit_notional: Decimal = Decimal('500'),
) -> CandidateOutcome:
    """Label a grid decision from the first executable interval trade.

    Entry benchmark: the 15-minute kline open, which is the first trade price
    after the decision boundary. Candidates with no trades are never generated.
    Exit liquidity is measured conservatively in the next five *full* one-minute
    bars after the crossing minute, excluding volume that may precede the cross.
    """
    by_15m = _bar_map(bars_15m)
    entry_bar = by_15m[decision_time]
    entry_price = entry_bar.open
    entry_notional = entry_bar.quote_volume
    entry_trades = entry_bar.trades
    entry_liquid = entry_notional >= min_entry_notional
    target_price = entry_price * (Decimal('1') + threshold_pct / Decimal('100'))
    horizon_end = decision_time + timedelta(minutes=horizon_minutes)

    forward_15m = [bar for bar in bars_15m if decision_time <= bar.open_time < horizon_end]
    max_high = max((bar.high for bar in forward_15m), default=entry_price)
    max_gain = (max_high / entry_price - Decimal('1')) * Decimal('100') if entry_price > 0 else Decimal('0')

    target_reached = max_high >= target_price
    crossing: datetime | None = None
    exit_notional = Decimal('0')
    exit_trades = 0
    liquidity_assessment_complete = not target_reached
    if target_reached and bars_1m:
        forward_1m = [bar for bar in bars_1m if decision_time <= bar.open_time < horizon_end]
        for bar in forward_1m:
            if bar.high >= target_price:
                crossing = bar.open_time
                break
        if crossing is not None:
            exit_start = crossing + timedelta(minutes=1)
            exit_end = exit_start + timedelta(minutes=exit_liquidity_minutes)
            exit_bars = [bar for bar in bars_1m if exit_start <= bar.open_time < exit_end]
            liquidity_assessment_complete = (
                len(exit_bars) == exit_liquidity_minutes
                and all(
                    bar.open_time == exit_start + timedelta(minutes=offset)
                    for offset, bar in enumerate(exit_bars)
                )
            )
            if liquidity_assessment_complete:
                for bar in exit_bars:
                    exit_notional += bar.quote_volume
                    exit_trades += bar.trades

    exit_liquid = bool(liquidity_assessment_complete and target_reached and exit_notional >= min_exit_notional)
    actionable = bool(target_reached and entry_liquid and liquidity_assessment_complete and exit_liquid)
    minutes_to_cross = (
        max(0, int((crossing - decision_time).total_seconds() // 60)) if crossing is not None else None
    )
    return CandidateOutcome(
        decision_time=decision_time,
        split=split,
        entry_price=entry_price,
        entry_quote_notional=entry_notional,
        entry_trade_count=entry_trades,
        entry_liquid=entry_liquid,
        target_price=target_price,
        target_reached=target_reached,
        crossing_minute=crossing,
        minutes_to_cross=minutes_to_cross,
        max_forward_high=max_high,
        max_forward_gain_pct=max_gain,
        exit_quote_notional=exit_notional,
        exit_trade_count=exit_trades,
        exit_liquid=exit_liquid,
        liquidity_assessment_complete=liquidity_assessment_complete,
        actionable_10pct=actionable,
    )
